version: "3.9"

include:
  - airflow/docker-compose.airflow.yml
  - postgresql/docker-compose.postgresql.yml
  - trino/docker-compose.trino.yml
  - redis/docker-compose.redis.yml
  - minio/docker-compose.minio.yml
  - qdrant/docker-compose.qdrant.yml
  - ollama/docker-compose.ollama.yml
  - mongodb/docker-compose.mongodb.yml
  - api/docker_compose.api_layer.yml
  - bot/docker_compose.bot.yml

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  qdrant_data:
  mongodb_data:
