version: 2

sources:
  - name: job_raw
    database: postgresql
    schema: staging

    tables:
      - name: topcv_data_job
        description: "Raw job data crawled from TopCV"

      - name: itviec_data_job
        description: "Raw job data crawled from ITViec"

  - name: bronze_layer
    schema: bronze

    tables:
      - name: bronze_ingest_itviec

      - name: bronze_ingest_topcv

  - name: audit_layer
    database: postgresql
    schema: audit

    tables:
      - name: master_job_elt_audit
