version: 2

models:
  - name: bronze_ingest_topcv
    columns:
      - name: url
        tests:
          - not_null
          - unique
      - name: descriptions
        tests:
          - not_null
      - name: requirements
        tests:
          - not_null
      - name: experiences
        tests:
          - not_null

  - name: bronze_ingest_itviec
    columns:
      - name: url
        tests:
          - not_null
      - name: descriptions
        tests:
          - not_null
      - name: requirements_and_experiences
        tests:
          - not_null
